image: jakzal/phpqa:php7.4

before_script:
    - cd api && composer install --no-interaction

cache:
    paths:
        - api/vendor/

stages:
    - security-checker
    - coding-standards
    - tests

security-checker:
    stage: security-checker
    script:
        - local-php-security-checker  --path=./composer.lock
    artifacts:
        reports:
            junit:
                - security-checker-report.xml
    allow_failure: false

phpcs:
    stage: coding-standards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: coding-standards
    script:
        - phpstan analyse ./src
    allow_failure: false

phpunit:
    image: php:7.4-apache
    stage: tests
    services:
        - name: mysql:8.0.29
          alias: mysql
    variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: json_to_csv
        DATABASE_URL: 'mysql://root:root@mysql:3306/json_to_csv'
    before_script:
        - apt-get update && apt-get install -y git libzip-dev
        - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
        - docker-php-ext-install mysqli pdo pdo_mysql zip
        - cd api && composer install --no-interaction
        - php bin/console doctrine:database:drop --env=test --if-exists --force
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:migration:migrate --env=test --no-interaction
        - php bin/console doctrine:fixtures:load --env=test --no-interaction
    cache:
        paths:
            - api/vendor/
    script:
        - php bin/phpunit
    allow_failure: false
