image: jakzal/phpqa:php8.1

before_script:
    - cd api && composer install

cache:
    paths:
        - api/vendor/

stages:
    - security-checker
    - coding-standards

security-checker:
    stage: security-checker
    script:
        - curl -L  https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_386 --output local-php-security-checker
        - chmod +x local-php-security-checker
        - ./local-php-security-checker --format=junit --path=./composer.lock > security-checker-report.xml
    artifacts:
        reports:
            junit:
                - security-checker-report.xml
    allow_failure: false

phpcs:
    stage: coding-standards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: coding-standards
    script:
        - phpstan analyse ./src
    allow_failure: false
